### ISSUE TITLE
No API accounts have been configured in application properties.

### ISSUE THREAD

**Issue by fathiman** [paypal/adaptiveaccounts-sdk-java#8]
I'm using AdaptiveAccountsService.getVerifiedStatus() call.
Have passed configuration as a map AdaptiveAccountsService(configurationPayPalService.getConfigMap());
I have done the setup of the properties file as well :
acct.UserName = ******facilitator_api1.gmail.com
acct.Password = *************
acct.Signature = *******************************
acct.AppId=APP-appIdXX
acct.Mode=sandbox

Still ended up with the error saying
No API accounts have been configured in application properties
	at com.paypal.core.CredentialManager.getCredentialObject(CredentialManager.java:47)
	at com.paypal.core.nvp.PlatformAPICallPreHandler.getCredentials(PlatformAPICallPreHandler.java:374)

Where have I gone wrong?

**Comment by fathiman** [comment]
duplicate
